name: Build poi

on:
  push:
    paths:
      - 'apis/poi/**'
      - '.github/workflows/poi-build.yml'
  pull_request:
    paths:
      - 'apis/poi/**'
      - '.github/workflows/poi-build.yml'
    branches: [ main ]

env:
  ACR_NAME: ${{ secrets.ACR_NAME }} 
  ACR_USER: ${{ secrets.ACR_USER }} 
  IMAGE_NAME: devopsoh/api-poi 
  IMAGE_TAG: ${{ github.run_id }}

jobs:
  build_poi:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1
    - name: Install dependencies
      run: dotnet restore 'apis/poi/poi.sln'
    - name: Build
      run: dotnet build 'apis/poi/poi.sln' --configuration Release --no-restore
    - name: Test
      run: dotnet test 'apis/poi/tests/UnitTests/UnitTests.csproj' --no-restore --verbosity normal

    - name: Create Issue Action
      if: ${{ failure() }}
      uses: nashmaniac/create-issue-action@v1.1
      with:
        # Title of the issue
        title: Build failed
        # Token of the user that creates the issue
        token: ${{secrets.GITHUB_TOKEN}}
        # Assignees of the issue
        assignees: ${{github.actor}}
        
  push_to_acr:
    name: Build Docker Image and push to ACR
    needs: build_poi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and Tag Docker Image
        run: | 
          docker build . -t $ACR_NAME/$IMAGE_NAME:$IMAGE_TAG
        working-directory: apis/poi/web
      - name: Login to ACR 
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run:  docker login ${{ secrets.ACR_NAME }} -u ${{ secrets.ACR_USER }} -p ${{ secrets.ACR_PASSWORD }} 
      - name: Push to ACR
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          docker push $ACR_NAME/$IMAGE_NAME:$IMAGE_TAG
        
  publish_web_app:
    name: Deploy to Azure WebApp
    needs: [build_poi, push_to_acr]
    runs-on: ubuntu-latest
    steps:
     - uses: Azure/webapps-deploy@v2
     - name: Deploy image to production slot
     - with:
        # Name of the Azure Web App
        app-name: openhack7475poi
        # Enter an existing Slot other than the Production slot
        slot-name: production
        # Applies to Web App only: Path to package or folder. *.zip, *.war, *.jar or a folder to deploy
        # Applies to Web App Containers only: Specify the fully qualified container image(s) name. For example, 'myregistry.azurecr.io/nginx:latest' or 'python:3.7.2-alpine/'. For multi-container scenario multiple container image names can be provided (multi-line separated)
        images: $ACR_NAME/$IMAGE_NAME:$IMAGE_TAG
