# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build userprofile
on:
  push:
    paths:
      - 'apis/userprofile/**'
      - '.github/workflows/userprofile-build.yml'
  pull_request:
    paths:
      - 'apis/userprofile/**'
      - '.github/workflows/userprofile-build.yml'
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
      working-directory: ./apis/userprofile/  
    - run: npm run build --if-present
      working-directory: ./apis/userprofile/ 
    - run: npm test
      working-directory: ./apis/userprofile/ 

    - name: Create Issue Action
      if: ${{ failure() }}
      uses: nashmaniac/create-issue-action@v1.1
      with:
        # Title of the issue
        title: Build failed
        # Token of the user that creates the issue
        token: ${{secrets.GITHUB_TOKEN}}
        # Assignees of the issue
        assignees: ${{github.actor}}
        body: Workflow failed for commit ${{github.sha}}
